# Generated by Django 5.2.7 on 2025-10-26 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CounterPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=25)),
                ('City', models.CharField(default='', max_length=25)),
                ('airport', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('LEAVING', 'Leaving'), ('COMING', 'Coming')], max_length=10)),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('gate', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('departed', 'departed'), ('delayed', 'delayed'), ('arrived', 'arrived'), ('cancelled', 'cancelled')], default='scheduled', max_length=12)),
                ('airline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Flight.airline')),
                ('counterpart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flight.counterpart')),
            ],
        ),
    ]
