# Generated by Django 5.2.7 on 2025-10-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='type',
            field=models.CharField(choices=[('LEAVING', 'Leaving'), ('COMING', 'Coming')], default='LEAVING', max_length=10),
        ),
    ]
