# Generated by Django 5.2.7 on 2025-11-01 07:06

import Flight.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0002_alter_flight_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('icon', models.ImageField(upload_to=Flight.models.imageSaver_TrvConIcon)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=25)),
                ('city', models.CharField(default='', max_length=25)),
                ('Bio', models.TextField(default='')),
                ('landmarks', models.CharField(default='many restaurants and activity center', max_length=50)),
                ('image', models.ImageField(upload_to=Flight.models.imageSaver_Destination)),
                ('static_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('avg_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Travel_Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('Description', models.TextField(default='')),
                ('icon', models.ImageField(upload_to=Flight.models.imageSaver_TrvConIcon)),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.AddField(
            model_name='flight',
            name='Business_Class_Num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='Business_Class_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='Economy_Class_Num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='Economy_Class_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='First_Class_Num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='Premium_Economy_Num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='Premium_Economy_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='counterpart_airport',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Flight.airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flight.destination'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='counterpart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flight.destination'),
        ),
        migrations.CreateModel(
            name='Travel_Conditions_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('Description', models.TextField(default='')),
                ('conditions', models.ManyToManyField(to='Flight.travel_condition')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_cond_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Flight.travel_conditions_group'),
        ),
        migrations.DeleteModel(
            name='AirLine',
        ),
        migrations.DeleteModel(
            name='CounterPart',
        ),
    ]
