# Generated by Django 5.2.7 on 2025-11-01 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0003_airport_destination_travel_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='travel_cond_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Flight.travel_conditions_group'),
        ),
        migrations.AlterField(
            model_name='travel_conditions_group',
            name='conditions',
            field=models.ManyToManyField(blank=True, to='Flight.travel_condition'),
        ),
    ]
