# Generated by Django 5.2.7 on 2025-11-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0004_alter_destination_travel_cond_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='icon',
        ),
    ]
