# Generated by Django 5.2.7 on 2025-11-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0005_remove_airport_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='First_Class_Num_available',
            field=models.IntegerField(default=0),
        ),
    ]
