# Generated by Django 5.2.7 on 2025-11-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0006_flight_first_class_num_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
