# Generated by Django 5.2.7 on 2025-11-14 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0007_destination_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='travel_cond_group',
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_cond_group_back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='travel_cond_group_back', to='Flight.travel_conditions_group'),
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_cond_group_go',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='travel_cond_group_go', to='Flight.travel_conditions_group'),
        ),
    ]
