# Generated by Django 5.2.7 on 2025-11-15 05:21

import Flight.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0008_remove_destination_travel_cond_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='icon',
            field=models.ImageField(default='', upload_to=Flight.models.imageSaver_Airport),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='Business_Class_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='Economy_Class_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='First_Class_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='Premium_Economy_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(default='', max_length=60, unique=True),
        ),
        migrations.RemoveField(
            model_name='destination',
            name='travel_cond_group_back',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='travel_cond_group_go',
        ),
        migrations.AlterField(
            model_name='flight',
            name='Business_Class_Num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Business_Class_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Economy_Class_Num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Economy_Class_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='First_Class_Num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='First_Class_Num_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Premium_Economy_Num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Premium_Economy_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_cond_group_back',
            field=models.ManyToManyField(blank=True, related_name='travel_cond_group_back', to='Flight.travel_conditions_group'),
        ),
        migrations.AddField(
            model_name='destination',
            name='travel_cond_group_go',
            field=models.ManyToManyField(blank=True, related_name='travel_cond_group_go', to='Flight.travel_conditions_group'),
        ),
    ]
