# Generated by Django 5.2.7 on 2025-11-18 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0009_airport_icon_flight_business_class_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='Flight.destination'),
        ),
    ]
