# Generated by Django 5.2.7 on 2025-12-03 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0010_alter_airport_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='counterpart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterpart', to='Flight.destination'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='counterpart_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterpart_airport', to='Flight.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
