# Generated by Django 5.2.7 on 2025-12-03 11:50

import Flight.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0011_alter_flight_counterpart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_condition',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=Flight.models.imageSaver_TrvConIcon),
        ),
    ]
