# Generated by Django 5.2.7 on 2025-12-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0012_alter_travel_condition_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='landmarks',
            field=models.CharField(default='many restaurants and activity center', max_length=80),
        ),
    ]
