# Generated by Django 5.2.7 on 2025-12-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0013_alter_destination_landmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
