# Generated by Django 5.2.7 on 2025-12-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0014_alter_destination_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='travel_condition',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='travel_conditions_group',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
