# Generated by Django 5.2.7 on 2025-12-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0015_alter_airport_id_alter_flight_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_top_destination',
            field=models.BooleanField(default=False),
        ),
    ]
