# Generated by Django 5.2.7 on 2025-12-08 10:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0016_destination_is_top_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
