# Generated by Django 5.2.7 on 2025-10-27 06:05

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_pref', models.CharField(choices=[('EN', 'EN'), ('AR', 'AR')], default='EN', max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.imageSaver_profile)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
