# Generated by Django 5.2.7 on 2025-11-01 10:07

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_language_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='your phone number', max_length=128, null=True, region='SY', unique=True),
        ),
    ]
