# Generated by Django 5.2.7 on 2026-03-11 06:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Flight', '0018_alter_airport_icon_alter_travel_condition_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=100.0, help_text='Price in site currency.', max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price')),
                ('assistance', models.TextField(help_text='Assistance details.', verbose_name='Assistance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Special Assistance',
                'verbose_name_plural': 'Special Assistances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_type', models.CharField(choices=[('one_direction', 'One Direction'), ('two_direction', 'Two Direction')], default='one_direction', help_text='Is the booking one-way or round-trip?', max_length=20, verbose_name='Flight Type')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Booking Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded'), ('CHECKED_IN', 'Checked-in'), ('WAITING_BACK_FLIGHT', 'Waiting for Return Flight')], default='PENDING', help_text='PENDING: Awaiting payment; CONFIRMED: Paid; CANCELLED: User canceled; REJECTED: Airline rejected; COMPLETED: Trip finished; EXPIRED: Not confirmed; REFUNDED: Money refunded; CHECKED_IN: User checked in; WAITING_BACK_FLIGHT: Round-trip, outbound flight completed.', max_length=25, verbose_name='Status')),
                ('chears', models.PositiveIntegerField(help_text='How many seats were booked?', verbose_name='Seats Booked')),
                ('chears_checked_in_go', models.PositiveIntegerField(default=0, help_text='How many seats have completed check-in for outbound flight?', verbose_name='Checked-In Seats (Outbound)')),
                ('chears_checked_in_back', models.PositiveIntegerField(default=0, help_text='How many seats have completed check-in for return flight?', verbose_name='Checked-In Seats (Return)')),
                ('chear_type', models.CharField(choices=[('Economy', 'Economy Class'), ('Premium', 'Premium Economy'), ('Business', 'Business Class'), ('First', 'First Class')], help_text='Seat class chosen for this booking.', max_length=20, verbose_name='Seat Class')),
                ('price', models.DecimalField(decimal_places=2, help_text='Total cost of the booking.', max_digits=10, verbose_name='Total Price')),
                ('is_payed', models.BooleanField(default=False, help_text='Has the booking been paid?', verbose_name='Is Payed')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('flight_back', models.ForeignKey(blank=True, help_text='Return flight for two-direction bookings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_back', to='Flight.flight', verbose_name='Return Flight')),
                ('flight_go', models.ForeignKey(help_text='The outbound flight for this booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings_go', to='Flight.flight', verbose_name='Outbound Flight')),
                ('user', models.ForeignKey(help_text='User who created the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Flight Booking',
                'verbose_name_plural': 'Flight Bookings',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='AssistanceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Extra info from the user.', verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested at')),
                ('state', models.CharField(choices=[('pinned', 'Order placed and payment pending'), ('ready', 'Payment has been made and the service is ready'), ('done', 'The journey has been completed'), ('rejected', 'The service has been cancelled by the company'), ('canceled', 'The service was cancelled by the customer'), ('refunded', 'Money has been refunded')], default='pinned', help_text='Current status of the assistance request.', max_length=20, verbose_name='State')),
                ('is_payed', models.BooleanField(default=False, help_text='Has the service been paid for?', verbose_name='Is Payed')),
                ('user', models.ForeignKey(help_text='User who made the assistance request.', on_delete=django.db.models.deletion.CASCADE, related_name='assistance_orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('booking_flight', models.ForeignKey(default=1, help_text='Booking Flight for which the assistance is requested.', on_delete=django.db.models.deletion.CASCADE, related_name='assistance_orders', to='Service.bookingflight', verbose_name='Booking Flight')),
                ('special_assistance', models.ForeignKey(help_text='Which assistance service the user requested.', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='Service.specialassistance', verbose_name='Special Assistance')),
            ],
            options={
                'verbose_name': 'Assistance Order',
                'verbose_name_plural': 'Assistance Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
