# Generated by Django 5.2.7 on 2026-03-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingflight',
            name='chears_checked_in_back',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='How many seats have completed check-in for return flight?', null=True, verbose_name='Checked-In Seats (Return)'),
        ),
    ]
