# Generated by Django 5.2.7 on 2025-10-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='communication_Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Email', max_length=50)),
                ('link', models.URLField(default='google.com')),
            ],
        ),
    ]
