# Generated by Django 5.2.7 on 2026-04-30 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('Service', '0002_alter_bookingflight_chears_checked_in_back'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_type', models.CharField(choices=[('New Booking', 'New Booking'), ('Modify Booking', 'Modify Booking'), ('Flight Inquiry', 'Flight Inquiry'), ('Complaints & Suggestions', 'Complaints & Suggestions'), ('Refund Request', 'Refund Request'), ('Lost Baggage', 'Lost Baggage'), ('Other', 'Other')], default='Other', max_length=30)),
                ('message', models.TextField()),
                ('booking_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Service.bookingflight')),
            ],
        ),
    ]
