# Generated by Django 5.2.7 on 2026-04-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_user_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_contacts',
            name='send_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
