# Generated by Django 5.2.7 on 2025-11-05 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short headline for the article.', max_length=255)),
                ('summary', models.CharField(blank=True, help_text='Short summary shown in lists.', max_length=512)),
                ('description', models.TextField(help_text='Full article content.')),
                ('image_label', models.ImageField(blank=True, help_text='Representative image for the article.', null=True, upload_to='company/articles/labels/')),
                ('article_type', models.CharField(choices=[('News', 'News'), ('Breaking_News', 'Breaking News'), ('Ad', 'Advertisement'), ('discount', 'Discount'), ('Notification', 'Notification')], default='News', max_length=30)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(help_text='Title of the career/position.', max_length=255)),
                ('description', models.TextField(help_text='Full description of the job / responsibilities.')),
                ('positions', models.PositiveIntegerField(default=1, help_text='Number of open positions.')),
                ('L_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Lower bound of the salary.', max_digits=12, null=True)),
                ('U_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Upper bound of the salary.', max_digits=12, null=True)),
                ('experience', models.CharField(help_text="Experience required (e.g., '2+ years').", max_length=255)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Publication datetime.')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Investor name or company.', max_length=255)),
                ('icon', models.ImageField(blank=True, help_text='Icon or logo for the investor.', null=True, upload_to='company/investors/icons/')),
                ('bio', models.TextField(blank=True, help_text='Short biography or investor summary.')),
                ('report', models.FileField(blank=True, help_text='Investor report file (PDF, XLSX, etc.).', null=True, upload_to='company/investors/reports/')),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Partner name.', max_length=255)),
                ('icon', models.ImageField(blank=True, help_text='Partner logo/icon.', null=True, upload_to='company/partners/icons/')),
                ('description', models.TextField(blank=True, help_text='Short description of the partner.')),
                ('business_type', models.CharField(blank=True, help_text='Type of business.', max_length=255)),
                ('link', models.CharField(blank=True, help_text='Partner website URL.', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the social account (e.g., Facebook).', max_length=100)),
                ('link', models.CharField(help_text='Full URL to the social account/profile.', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image file for the article.', upload_to='company/articles/images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering index for image display.')),
                ('article', models.ForeignKey(help_text='The article to which this image belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Company.article')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
