# Generated by Django 5.2.7 on 2025-12-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='extra_images',
            field=models.ImageField(blank=True, help_text='Representative image for the article.', null=True, upload_to='company/articles/labels/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_label',
            field=models.CharField(default='No Images', help_text='Adding label to the images.', max_length=255),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
