# Generated by Django 5.2.7 on 2025-12-09 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_article_extra_images_alter_article_image_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('cv', models.FileField(blank=True, help_text='Uploaded CV file', null=True, upload_to='company/careers/applications/cv/')),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(help_text='The career/job this application belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='Company.career')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
