# Generated by Django 5.2.7 on 2025-12-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_careerapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='extra_images',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_label',
        ),
    ]
