# Generated by Django 5.2.7 on 2026-03-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_remove_article_article_type_remove_article_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('News', 'News'), ('Breaking_News', 'Breaking News'), ('Ad', 'Advertisement'), ('discount', 'Discount'), ('Notification', 'Notification')], default='News', max_length=30),
        ),
    ]
