# Generated by Django 5.2.7 on 2026-03-29 21:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_article_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='cv',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Uploaded CV file', max_length=255, null=True),
        ),
    ]
